[package]
name = "bevy_fmod_core"
description = "Idiomatic FMOD in Bevy"
version = "0.1.0"
readme = "../README.md"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.69"
bevy = "0.11.0"
bevy_mod_sysfail = "3.0.0"
libfmod = { git = "https://github.com/Salzian/libfmod", branch = "main" }