name: 'Setup Cache'
description: 'Sets up caching for Rust projects'

runs:
  using: "composite"
  steps:
    - name: Setup Cache for Registry and Build Artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}