name: 'Install platform dependencies'
description: 'Installs platform dependencies for the current OS'
inputs:
  os:
    description: 'The OS to install dependencies for'
    required: true

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.os == 'ubuntu-latest' }}
      name: Install ubuntu dependencies
      shell: bash
      run: sudo apt install -y libasound2-dev libudev-dev